// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDI9r2Vj2CeJICvc-RrINcDn8DLqC2rak',
    appId: '1:558918948925:web:bd777ae49de2a890967254',
    messagingSenderId: '558918948925',
    projectId: 'smartpantry-123',
    authDomain: 'smartpantry-123.firebaseapp.com',
    storageBucket: 'smartpantry-123.firebasestorage.app',
    measurementId: 'G-HSH4F53XY8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd2cnmlQf-V2SSPJcCNDU8Hr5rSDYhJLY',
    appId: '1:558918948925:android:bfad1ed36bfcf2bd967254',
    messagingSenderId: '558918948925',
    projectId: 'smartpantry-123',
    storageBucket: 'smartpantry-123.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCcF1VxzU0f5CTULKJmtt3JMgIEFClpm8',
    appId: '1:558918948925:ios:e5b18ecdf64e4c00967254',
    messagingSenderId: '558918948925',
    projectId: 'smartpantry-123',
    storageBucket: 'smartpantry-123.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCcF1VxzU0f5CTULKJmtt3JMgIEFClpm8',
    appId: '1:558918948925:ios:e5b18ecdf64e4c00967254',
    messagingSenderId: '558918948925',
    projectId: 'smartpantry-123',
    storageBucket: 'smartpantry-123.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDI9r2Vj2CeJICvc-RrINcDn8DLqC2rak',
    appId: '1:558918948925:web:99a3b7f4fa4b357e967254',
    messagingSenderId: '558918948925',
    projectId: 'smartpantry-123',
    authDomain: 'smartpantry-123.firebaseapp.com',
    storageBucket: 'smartpantry-123.firebasestorage.app',
    measurementId: 'G-XWHV08Y2DF',
  );
}
